# COMMENTED OUT - Will enable after database is created
# # AKS Outputs
# output "aks_cluster_name" {
#   description = "AKS cluster name"
#   value       = azurerm_kubernetes_cluster.aks.name
# }
#
# output "aks_cluster_id" {
#   description = "AKS cluster ID"
#   value       = azurerm_kubernetes_cluster.aks.id
# }
#
# output "aks_kube_config" {
#   description = "Kubernetes config as generated by the AKS cluster"
#   value       = azurerm_kubernetes_cluster.aks.kube_config_raw
#   sensitive   = true
# }
#
# output "aks_client_certificate" {
#   description = "Base64 encoded public certificate used by clients to authenticate to the Kubernetes cluster"
#   value       = azurerm_kubernetes_cluster.aks.kube_config.0.client_certificate
#   sensitive   = true
# }

# VM Outputs
output "vm_id" {
  description = "Virtual Machine ID"
  value       = azurerm_linux_virtual_machine.vm.id
}

output "vm_name" {
  description = "Virtual Machine name"
  value       = azurerm_linux_virtual_machine.vm.name
}

output "vm_public_ip" {
  description = "Virtual Machine public IP address"
  value       = azurerm_public_ip.vm.ip_address
}

output "vm_private_ip" {
  description = "Virtual Machine private IP address"
  value       = azurerm_network_interface.vm.private_ip_address
}

output "vm_ssh_command" {
  description = "SSH command to connect to the VM"
  value       = "ssh ${var.admin_username}@${azurerm_public_ip.vm.ip_address}"
}

# PostgreSQL Outputs
output "postgresql_server_fqdn" {
  description = "PostgreSQL server FQDN"
  value       = azurerm_postgresql_flexible_server.postgresql.fqdn
}

output "postgresql_server_id" {
  description = "PostgreSQL server ID"
  value       = azurerm_postgresql_flexible_server.postgresql.id
}

output "postgresql_connection_string" {
  description = "PostgreSQL connection string"
  value       = "postgresql://${var.postgresql_admin_username}:${var.postgresql_admin_password}@${azurerm_postgresql_flexible_server.postgresql.fqdn}:5432/atlas?sslmode=require"
  sensitive   = true
}

# COMMENTED OUT - Will enable after database is created
# # Storage Account Outputs
# output "storage_account_id" {
#   description = "Storage account ID"
#   value       = azurerm_storage_account.ameciclo.id
# }
#
# output "storage_account_name" {
#   description = "Storage account name"
#   value       = azurerm_storage_account.ameciclo.name
# }
#
# output "storage_account_primary_blob_endpoint" {
#   description = "Storage account primary blob endpoint"
#   value       = azurerm_storage_account.ameciclo.primary_blob_endpoint
# }
#
# # Container Registry Outputs
# output "container_registry_login_server" {
#   description = "Container Registry login server"
#   value       = azurerm_container_registry.acr.login_server
# }
#
# output "container_registry_id" {
#   description = "Container Registry ID"
#   value       = azurerm_container_registry.acr.id
# }

# Resource Group Outputs
output "resource_group_name" {
  description = "Resource group name"
  value       = azurerm_resource_group.ameciclo.name
}

output "resource_group_id" {
  description = "Resource group ID"
  value       = azurerm_resource_group.ameciclo.id
}

