networks:
  kestra-network:
    driver: overlay
    attachable: true

volumes:
  kestra_data:
  kestra_plugins:
  kestra_db:

services:
  kestra:
    image: kestra/kestra:${KESTRA_VERSION:-latest}
    environment:
      - JAVA_OPTS=${KESTRA_JAVA_OPTS:--Xms256m -Xmx512m}
    volumes:
      - kestra_data:/app/storage
      - kestra_plugins:/app/plugins
      - kestra_db:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    ports:
      - "${KESTRA_PORT:-8084}:8080"
    networks:
      - kestra-network
    user: "root"
    command: server local
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: ${KESTRA_MEMORY_LIMIT:-1g}
