---
# Kong ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: ameciclo
data:
  KONG_DATABASE: "postgres"
  KONG_PG_PORT: "5432"
  KONG_PG_DATABASE: "kong"
  KONG_PG_SSL: "on"
  KONG_PROXY_LISTEN: "0.0.0.0:80, 0.0.0.0:443 ssl"
  KONG_PROXY_ACCESS_LOG: "/dev/stdout"
  KONG_PROXY_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001"
  KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
  KONG_ADMIN_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
  KONG_ADMIN_GUI_AUTH: "basic-auth"
  KONG_LOG_LEVEL: "notice"
  KONG_LUA_SSL_TRUSTED_CERTIFICATE: "system"

---
# Kong Migrations Job
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
  namespace: ameciclo
spec:
  template:
    spec:
      serviceAccountName: kong
      containers:
      - name: kong-migrations
        image: kong:latest
        command: ["kong", "migrations", "bootstrap"]
        envFrom:
        - configMapRef:
            name: kong-config
        env:
        - name: KONG_PG_HOST
          valueFrom:
            secretKeyRef:
              name: kong-postgres-secret
              key: host
        - name: KONG_PG_USER
          valueFrom:
            secretKeyRef:
              name: kong-postgres-secret
              key: username
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgres-secret
              key: password
      restartPolicy: Never
  backoffLimit: 3

---
# Kong Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: ameciclo
  labels:
    app: kong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      serviceAccountName: kong
      containers:
      - name: kong
        image: kong:latest
        ports:
        - name: proxy
          containerPort: 80
        - name: proxy-ssl
          containerPort: 443
        - name: admin
          containerPort: 8001
        - name: admin-gui
          containerPort: 8002
        envFrom:
        - configMapRef:
            name: kong-config
        env:
        - name: KONG_PG_HOST
          valueFrom:
            secretKeyRef:
              name: kong-postgres-secret
              key: host
        - name: KONG_PG_USER
          valueFrom:
            secretKeyRef:
              name: kong-postgres-secret
              key: username
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgres-secret
              key: password
        livenessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
# Kong Service
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: ameciclo
  labels:
    app: kong
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: kong

---
# Kong Admin Service
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: ameciclo
  labels:
    app: kong
spec:
  type: ClusterIP
  ports:
  - name: admin
    port: 8001
    targetPort: 8001
  - name: admin-gui
    port: 8002
    targetPort: 8002
  selector:
    app: kong

---
# Kong ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong
  namespace: ameciclo

