---
# Cyclist Counts Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyclist-counts
  namespace: ameciclo
  labels:
    app: cyclist-counts
    service: atlas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cyclist-counts
  template:
    metadata:
      labels:
        app: cyclist-counts
        service: atlas
    spec:
      containers:
      - name: cyclist-counts
        image: ghcr.io/ameciclo/atlas/cyclist-counts:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: PORT
          value: "3002"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: atlas-postgres-secret
              key: connection-string
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
# Cyclist Counts Service
apiVersion: v1
kind: Service
metadata:
  name: cyclist-counts
  namespace: ameciclo
  labels:
    app: cyclist-counts
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3002
    targetPort: 3002
  selector:
    app: cyclist-counts

