---
# Traffic Deaths Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-deaths
  namespace: ameciclo
  labels:
    app: traffic-deaths
    service: atlas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traffic-deaths
  template:
    metadata:
      labels:
        app: traffic-deaths
        service: atlas
    spec:
      containers:
      - name: traffic-deaths
        image: ghcr.io/ameciclo/atlas/traffic-deaths:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3003
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: PORT
          value: "3003"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: atlas-postgres-secret
              key: connection-string
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
# Traffic Deaths Service
apiVersion: v1
kind: Service
metadata:
  name: traffic-deaths
  namespace: ameciclo
  labels:
    app: traffic-deaths
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3003
    targetPort: 3003
  selector:
    app: traffic-deaths

