kestra:
  repository:
    type: memory
  queue:
    type: memory
  storage:
    type: local
    local:
      base-path: /app/storage
  server:
    port: 8080
    basic-auth:
      enabled: true
      username: admin
      password: kestra
  metrics:
    enabled: true
    prometheus:
      enabled: true
  # Uncomment to enable UI customization
  # ui:
  #   title: "Ameciclo Kestra"
  #   logo: "https://example.com/logo.png"
  #   theme:
  #     primary: "#3f51b5"
  #     secondary: "#f50057"
  #     accent: "#8bc34a"
  #     error: "#ff5722"
  #     warning: "#ffc107"
  #     info: "#2196f3"
  #     success: "#4caf50"
