---
- name: Install Docker and Portainer in Swarm mode
  hosts: all
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Get private IP address
      shell: ip -4 addr show eth0 | grep -oP '(?<=inet\s)10\.\d+(\.\d+){2}'
      register: private_ip
      changed_when: false

    - name: Initialize Docker Swarm
      command: "docker swarm init --advertise-addr {{ private_ip.stdout }}"
      register: swarm_init
      changed_when: "'This node is already part of a swarm' not in swarm_init.stderr"
      failed_when: "swarm_init.rc != 0 and 'This node is already part of a swarm' not in swarm_init.stderr"

    - name: Create Portainer compose file
      copy:
        dest: /root/portainer-compose.yml
        content: |
          version: "3.8"
          services:
            portainer:
              image: portainer/portainer-ce:latest
              command: -H tcp://tasks.portainer_agent:9001 --tlsskipverify
              ports:
                - "9000:9000"
                - "8000:8000"
              volumes:
                - portainer_data:/data
              networks:
                - portainer_network
              deploy:
                mode: replicated
                replicas: 1
                placement:
                  constraints: [node.role == manager]
                restart_policy:
                  condition: any

            portainer_agent:
              image: portainer/agent:latest
              environment:
                # REQUIRED: Should be equal to the service name prefixed by tasks.
                - AGENT_CLUSTER_ADDR=tasks.portainer_agent
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - /var/lib/docker/volumes:/var/lib/docker/volumes
              networks:
                - portainer_network
              deploy:
                mode: global
                restart_policy:
                  condition: any

          networks:
            portainer_network:
              driver: overlay
              attachable: true

          volumes:
            portainer_data:
              external: false

    - name: Deploy Portainer stack
      command: docker stack deploy -c /root/portainer-compose.yml portainer
      register: stack_result
      changed_when: "'Updating service' in stack_result.stdout or 'Creating service' in stack_result.stdout"

    - name: Wait for Portainer to be available
      wait_for:
        host: "{{ ansible_host }}"
        port: 9000
        delay: 10
        timeout: 300
