x-kong-config: &kong-env # Database settings
  KONG_DATABASE: ${KONG_DATABASE:-postgres}
  KONG_PG_HOST: ${KONG_PG_HOST:-your-db-host.example.com}
  KONG_PG_PORT: ${KONG_PG_PORT:-25060}
  KONG_PG_USER: ${KONG_PG_USER:-doadmin}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
  KONG_PG_SSL: ${KONG_PG_SSL:-on}

  # Proxy settings
  KONG_PROXY_LISTEN: ${KONG_PROXY_LISTEN:-0.0.0.0:80, 0.0.0.0:443 ssl}
  KONG_PROXY_ACCESS_LOG: /dev/stdout
  KONG_PROXY_ERROR_LOG: /dev/stderr

  # Admin API settings
  KONG_ADMIN_LISTEN: ${KONG_ADMIN_LISTEN:-0.0.0.0:8001}
  KONG_ADMIN_ACCESS_LOG: /dev/stdout
  KONG_ADMIN_ERROR_LOG: /dev/stderr

  # Kong Manager settings
  KONG_ADMIN_GUI_LISTEN: ${KONG_ADMIN_GUI_LISTEN:-0.0.0.0:8002}
  KONG_ADMIN_GUI_AUTH: ${KONG_ADMIN_GUI_AUTH:-basic-auth}
  KONG_ADMIN_GUI_SESSION_CONF: '{"secret":"${KONG_ADMIN_GUI_SESSION_SECRET}","storage":"kong","cookie_secure":false}'

  # Misc settings
  KONG_LOG_LEVEL: ${KONG_LOG_LEVEL:-notice}
  KONG_LUA_SSL_TRUSTED_CERTIFICATE: system

volumes:
  kong_data: {}
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  kong-net:
    external: false

services:
  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    environment:
      <<: *kong-env
    networks:
      - kong-net
    restart: on-failure

  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations up && kong migrations finish
    environment:
      <<: *kong-env
    networks:
      - kong-net
    restart: on-failure

  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    environment:
      <<: *kong-env
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
    networks:
      - kong-net
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "8001:8001/tcp"
      - "8444:8444/tcp"
      - "8002:8002/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
    security_opt:
      - no-new-privileges
