global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load and evaluate rules in this file
rule_files:
  - "alert.rules"

# A scrape configuration containing endpoints to scrape
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "docker"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_swarm_task_name]
        target_label: container_name

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"] # Internal port remains 8080

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "kestra"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["kestra:8080"]
